TandCs = [
"(IMPORTANT): This proposal incorporates by reference the terms and conditions which are attached to this document. All work is to be performed Monday through Friday during normal Johnson Controls, Inc. (JCI) business hours unless otherwise noted. This proposal, or any accepted alternates, are hereby accepted by Customer, and JCI is authorized to proceed with the work; subject, however, to credit approval by JCI, Milwaukee, Wisconsin.",
"TERMS AND CONDITIONS",
"By accepting this proposal, Customer agrees to be bound by the following terms and conditions:",

"1. SCOPE OF WORK. This proposal is based upon the use of straight time labor only. Plastering, patching, and painting are excluded. Disinfecting of chiller condenser and cooling tower water systems and components for biohazards, such as but not limited to Legionella, are excluded unless otherwise specifically stated in this agreement. In-line duct and piping devices, including, but not limited to valves, dampers, humidifiers, wells, taps, flow meters, orifices, etc., if required hereunder to be furnished by JCI, shall be distributed and installed by others under JCI’s supervision but at no additional cost to JCI. Customer agrees to provide JCI with required field utilities (electricity, toilets, drinking water, project hoist, elevator service, etc.) without charge. JCI agrees to keep the job site clean of debris arising out of its own operations. Customer shall not back charge JCI for any costs or expenses without JCI’s written consent. Unless specifically noted in the statement of the scope of work or services undertaken by JCI under this agreement, JCI’s obligations under this agreement expressly exclude any language or provision of the agreement elsewhere contained which may authorize or empower the Customer to change, modify, or alter the scope of work or services to be performed by JCI and shall not operate to compel JCI to perform any work relating to Hazards or Biohazards, such as but not limited to Legionella, without JCI’s express written consent.",

"2. INVOICE AND PAYMENTS. JCI may invoice Customer monthly for all materials delivered to the job site or to an off-site storage facility and for all work performed on-site and off-site. Customer shall pay JCI at the time Customer signs this agreement an advance payment equal to 10% of the contract price, which advance payment shall be credited against the final payment (but not any progress payment) due hereunder. Payment is due to JCI upon Customer’s receipt of JCI’s invoice and shall be paid by Customer within 30 days. Invoicing disputes must be identified by Customer in writing within 21 days of the date of the invoice. Payment of any disputed amounts are due and payable upon resolution of such dispute. All other amounts remain due within 30 days. Failure to make payments when due will give JCI, without prejudice to any other right or remedy, the right to: (i) stop performing any services, withhold deliveries of equipment and other materials, terminate or suspend any unpaid software licenses, and/or terminate this agreement; and (ii) charge Customer interest on the amounts unpaid at a rate equal to the lesser of one and one half (1.5) percent per month or the maximum rate permitted under applicable law, until payment is made in full. Customer will pay all of JCI’s reasonable collection costs (including legal fees and expenses). In the event of Customer’s default, the balance of any outstanding amounts will be immediately due and payable. Lien waivers will be furnished upon request, as the work progresses, to the extent payments are received.",

"3. MATERIALS. If the materials or equipment included in this proposal become temporarily or permanently unavailable for reasons beyond the control and without the fault of JCI, then in the case of such temporary unavailability, the time for performance of the work shall be extended to the extent thereof, and in the case of permanent unavailability, JCI shall (a) be excused from furnishing said materials or equipment, and (b) be reimbursed for the difference between the cost of the materials or equipment permanently unavailable and the cost of a reasonably available substitute therefore.",

"4. EQUIPMENT WARRANTY. JCI warrants that equipment manufactured or labeled by JCI shall be free from defects in material and workmanship arising from normal usage for a period of one year. Only if JCI installs or furnishes a piece of equipment under this agreement, and that equipment is covered by a warranty from a manufacturer other than JCI, JCI will transfer the benefits of that manufacturer’s warranty to Customer. All transportation charges incurred in connection with the warranty for equipment and/or materials not installed by JCI shall be borne by Customer. These warranties shall not extend to any equipment that has been abused, altered, misused or repaired by Customer or third parties without the supervision of and prior written approval of JCI, or if JCI serial numbers or warranty date decals have been removed or altered. Customer must promptly report any failure of the equipment to JCI in writing.",

"5. LIMITED WARRANTY. JCI warrants its workmanship or that of its agents (Technicians) in relation to installation of equipment for a period of ninety (90) days from date of installation. Customer shall bear all labor costs associated with replacement of failed equipment still under JCI’s equipment warranty or the original manufacturer’s warranty, but outside the terms of this express labor warranty. All warranty labor shall be executed on normal business days during JCI normal business hours. These warranties do not extend to any equipment which has been repaired by others, abused, altered, or misused in any way, or which has not been properly and reasonably maintained. THESE WARRANTIES ARE IN LIEU OF ALL OTHER WARRANTIES, EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THOSE OF MERCHANTABILITY AND FITNESS FOR A SPECIFIC PURPOSE. UNDER NO CIRCUMSTANCES SHALL JCI BE LIABLE FOR ANY SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES ARISING FROM OR RELATING TO ANY DEFECT IN MATERIAL OR WORKMANSHIP OF EQUIPMENT OR THE PERFORMANCE OF SERVICES. JCI makes no and specifically disclaims all representations or warranties that the services, products, software or third party product or software will be secure from cyber threats, hacking or other similar malicious activity.",

"6. LIABILITY. To the maximum extent permitted by law, in no event shall JCI and its affiliates and their respective personnel, suppliers and vendors (“JCI Parties”) be liable to you or any third party under any cause of action or theory of liability even if advised of the possibility of such damages, for any: (a) special, incidental, consequential, punitive, or indirect damages; (b) lost profits, revenues, data, customer opportunities, business, anticipated savings, or goodwill; (c) business interruption; or (d) data loss or other losses arising from viruses, ransomware, cyber-attacks or failures or interruptions to network systems. In any case, the entire aggregate liability of the JCI Parties under this proposal for all damages, losses, and causes of action (whether in contract, tort (including negligence), or otherwise) shall be limited to the amounts payable to JCI hereunder.",

"7. TAXES. The price of this proposal does not include duties, sales, use, excise, or other taxes, unless required by federal, state, or local law. Customer shall pay, in addition to the stated price, all taxes not legally required to be paid by JCI or, alternatively, shall provide JCI with acceptable tax exemption certificates. JCI shall provide Customer with any tax payment certificate upon request and after completion and acceptance of the work.",

"8. DELAYS. JCI shall not be liable for any delay in the performance of the work resulting from or attributed to acts of circumstance beyond JCI’s control, including but not limited to; acts of God, fire, riots, labor disputes, conditions of the premises, acts or omissions of the Customer, Owner, or other Contractors or delays caused by suppliers or subcontractors of JCI, etc.",

"9. COMPLIANCE WITH LAWS. JCI shall comply with all applicable federal, state, and local laws and regulations, and shall obtain all temporary licenses and permits required for the prosecution of the work. Licenses and permits a permanent nature shall be procured and paid for by the Customer.",

"10. PRICING; PAYMENT. JCI may increase prices upon notice to the Customer to reflect increases in material and labor costs. Customer shall pay all invoices when due in accordance with the payment terms provided for herein, and such payment is a condition precedent to JCI’s obligation to provide products or perform services hereunder. In issuing any purchase order related to or arising out of this proposal and notwithstanding any language to the contrary therein, Customer acknowledges and agrees that any and all JCI invoices for an amount greater than $25,000 shall be paid via wire transfer, check or money order, and that Customer shall not make, nor will JCI accept, payment in excess of $25,000 in the form of a credit card, debit card, or other similar payment device.",

"11. DISPUTES. All disputes involving more than $15,000.00 shall be resolved by arbitration in accordance with the rules of the American Arbitration Association. The prevailing party shall recover all legal costs and attorneys’ fees incurred as a result. Nothing here shall limit any rights under construction lien laws.",

"12. INSURANCE. Insurance coverage in excess of JCI’s standard limits will be furnished when requested and required. No credit will be given or premium paid by JCI for insurance afforded by others.",

"13. INDEMNITY. The Parties hereto agree to indemnify each other from any and all liabilities, claims, expenses, losses or damages, including attorney’s fees which may arise in connection with the execution of the work herein specified and which are caused, by the negligent act or omission of the indemnifying Party.",

"14. CUSTOMER RESPONSIBILITIES. Customer is solely responsible for the establishment, operation, maintenance, access, security and other aspects of its computer network (“Network”) and shall supply Johnson Controls secure Network access for providing its services. Products networked, connected to the internet, or otherwise connected to computers or other devices must be appropriately protected by Customer and/or end user against unauthorized access. Customer is responsible to take appropriate measures, including performing back-ups, to protect information, including without limit data, software, or files (collectively “Data”) prior to receiving the service or products.",

"15. FORCE MAJEURE. JCI shall not be responsible for delays, interruption or failure to perform due to causes beyond its control, including but not limited to material shortages, work stoppages, fires, civil disobedience or unrest, cyber-attacks, viruses, ransomware, failures or interruptions to network systems, data breaches, severe weather, fire or any other cause beyond the reasonable control of JCI.",

"16. OCCUPATIONAL SAFETY AND HEALTH. The Parties hereto agree to notify each other immediately upon becoming aware of an inspection under, or any alleged violation of the, Occupational Safety and Health Act relating in any way to the project or project site.",

"17. ONE-YEAR CLAIMS LIMITATION. No claim or cause of action, whether known or unknown, shall be brought against JCI more than one year after the claim first arose. Except as provided for herein, JCI’s claims must also be brought within one year. Claims for unpaid contract amounts are not subject to the one-year limitation.",

"18. CONNECTED SERVICES (APPLIES ONLY TO LARGE-TONNAGE, WATER-COOLED CHILLERS). JCI will provide a cellular modem (“Gateway Device” owned by JCI) or Customer will supply a network connection suitable to establish a remote connection with Customer’s Equipment to permit JCI to perform first-year warranty services, troubleshooting, quarterly health reports, and meet service levels, including remote diagnostic, monitoring and repair services. Customer will benefit from being able to access chiller information from JCI Connected Chillers from a mobile smart device. The Gateway Device shall remain JCI’s property, and JCI may upon reasonable notice remove it at any time. If Customer does not permit JCI to connect via a connection validated by JCI for the Equipment and the service representative must therefore be dispatched to the Customer site, then the Customer will pay JCI at JCI’s then-current standard applicable contract regular time and/or overtime rate for services performed by the service representative. Connectivity charges are covered under the first year of warranty. Connected Chiller’s cellular modem device (“Gateway Device”) as well as concierge support service will be covered by JCI in the first year of warranty, (12 months from startup or 18 months from ship date, whichever comes first). After the first year of warranty, Customer is responsible for subsequent years of Connected Chiller Services payable to JCI at current market MLP rates. Unless Customer specifically requests in writing that JCI disable the remote connection, the remote connection will continue to connect to Customer’s Equipment until the expiration of the first year of warranty and/or any subsequent years’ Service Agreement. Connected Chiller Services shall begin upon startup of Equipment. For Equipment not covered by a current Service Agreement, JCI disclaims any obligation to monitor such products via a remote connection or advise Customer of any possible Equipment error or malfunction.",

"19. ENTIRE AGREEMENT. This proposal, upon acceptance, shall constitute the entire agreement between the parties and supersedes any prior representations or understandings.",

"20. CHANGES. No change or modification of any of the terms and conditions stated herein shall be binding upon JCI unless accepted by JCI in writing.",
]